### ISSUE TITLE
suggestions: misc edits

### ISSUE THREAD

**Issue by stharrold** [stefano-meschiari/Jupiter-analogs-article#4]
My wife read your article, and since she edits out of habit, she had a lot to say. We both really liked it! She may be closer to your intended audience, so here's her feedback:
"""
I only have the vaguest idea of what the period means. I took astronomy in college, and I'm married to a former astronomy guy.

Shorten some of your sentences, especially when they're conveying dense information. I'd rewrite the sentence with "a cursory look at the figure..." more like: "The figure shows that Earth, Jupiter, Saturn and Uranus occupy 'empty' parts of the diagram. This seems to indicate that the majority of planetary systems do not resemble our own Solar System." Fewer words and shorter sentences are really key when trying to make complex information comprehensible to people outside your field.

I did not realize that "super-Earths" and "long period gas giants" could be seen on the chart, either in their presence or lack. Maybe explain that the blue cluster in the bottom left are super-Earths? I'd suggest removing the comments about circular orbits for clarity.

What is a "true solar system"? Is that the same as a Solar System analog?

The three paragraphs under "Are Jupiter-like Planets rare?" should be like two sentences because omg I don't care. Questions that I had: How did a high school student get involved with this? That's way more interesting than his co-authors, the telescope, the procedure, blah blah blah.

Suggested title: "Is the Solar System Weird?" Weird is more interesting than "typical," but I also like dragging in the high school student. But then you never really came back to the fact that it's cool that a high school student is making an actual scientific contribution. I feel ripped off by your title.
"""
(We both actually really did like it :) )

**Comment by stefano-meschiari** [comment]
Oh wow, thank you so much to both you and your wife for taking the time to write these detailed comments! I'm implementing the bulk of them in my next draft. 

I also agree somewhat that in terms of what's interesting, _high school students gets involved in science_ > _the science itself_, but the publication itself has a strong research slant. I'll discuss that point with the editor.

**Comment by stefano-meschiari** [comment]
Implemented most of the suggestions in final version.
